# Spring config Properties
spring.application.name=WEGpark
spring.config.import=optional:file:.env[.properties]

#Database Config
server.port=8080
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}?currentSchema=infra

#Jpa
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=infra

#Datasource pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=20000

#Schemas
spring.modulith.events.jdbc.schema=infra

#Flyway
spring.flyway.default-schema=infra
spring.flyway.schemas=infra,auth,rh,park
spring.flyway.enabled=true

security.variables.private-key=${JWT_PRIVATE_KEY}
security.variables.public-key=${JWT_PUBLIC_KEY}
security.variables.token-expiration-time-minutes=60

#Mail Config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.default-encoding=UTF-8

spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.test-connection = false

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000