CREATE TABLE park.occurrence (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    uuid UUID DEFAULT uuidv7() UNIQUE NOT NULL,
    date_hour TIMESTAMP NOT NULL,
    location VARCHAR(255) NOT NULL,
    gate VARCHAR(255) NOT NULL,
    occurrence_type VARCHAR(50) NOT NULL
);
